version: '3.4'
services:
  bifrost-ui:
    image: ${DOCKER_REGISTRY_ADDRESS}/bifrost-ui:${DOCKER_TAG_VERSION}
    container_name: bifrost-ui
    ports:
      - 5001:80
    environment:
      NODE_ENV: '${NODE_ENV}'
    deploy:
      replicas: ${replicas}
      update_config:
        parallelism: 2
        delay: 2s
      restart_policy:
        condition: on-failure
